"""`metagx project` — scaffold a complete, runnable analysis folder from a config.

This is the end-user deliverable, generated BY the tool (not hand-assembled): given a validated
``config.yaml`` it writes the config, a sample-sheet template, a **collision-safe per-config conda
env**, an install/env-making script, a run script, an optional HPC profile, and a README.

The collision/dependency guarantee (see ``wiring`` invariant I) is enforced here by *splitting*
a config's tools into two buckets, never mixing colliders:

  * **tailored core env** — the tools that live in the curated, collision-free ``environment.yml``
    (``report.active_core_packages``). Written to ``env.yaml`` and put on PATH.
  * **``--use-conda`` tools** — everything the config activates that is NOT in the core env; each
    has its own isolated ``workflow/envs/*.yaml`` (that's *why* it's isolated — size or a
    dependency clash like abricate's samtools-0.1.x pin). Snakemake provisions these per-rule.

``use_conda`` is turned on **iff** the config needs any per-rule tool, so a pure-core run (e.g.
gut-profiling) creates no per-rule envs at all, and a run that needs GTDB-Tk/AMR/etc. self-provisions
exactly those — for *any* config, automatically.
"""
from __future__ import annotations

import os
from typing import Any, Dict, List, Optional

import yaml

from . import report, runner, schedulers

# The install source baked into every generated 00_setup.sh. Kept in ONE place and overridable at
# run time via the METAGX_REPO env var — point it at the canonical repo or a pinned release tag for
# a reproducible hand-off (a moving default means a folder handed out today may install a different
# metagx tomorrow).
METAGX_REPO_URL = "https://github.com/MdRasheduz-zaman/metagenomics-skill.git"

_SHORT_PLATFORMS = {"illumina", "mgi", "bgi"}


def plan_env(cfg: Dict[str, Any], env_yml_path: Optional[str]) -> Dict[str, Any]:
    """Collision-safe environment plan for a config (pure; no IO beyond reading env_yml_path).

    Returns ``{env_name, core_packages, per_rule_tools, use_conda}``. A tool is a ``per_rule``
    tool exactly when its conda package is not in the tailored core env — and invariant I
    guarantees every such tool has an isolated ``workflow/envs/*.yaml``, so ``--use-conda`` can
    provision it. ``use_conda`` is therefore the honest "does this config need per-rule envs?"."""
    active = [t for t in set(report.active_tools(cfg)) if t != "snakemake"]
    core_bases = set(report._env_yaml_packages(env_yml_path))
    per_rule = sorted(t for t in active if report.conda_package(t) not in core_bases)
    return {
        "env_name": f"metagx-{cfg.get('project', 'run')}",
        "core_packages": report.active_core_packages(cfg, env_yml_path),
        "per_rule_tools": per_rule,
        "use_conda": bool(per_rule),
    }


# --------------------------------------------------------------------------- #
# File templates (parameterized; keep them correct + minimal)                 #
# --------------------------------------------------------------------------- #
def _samples_template(platform: str, cfg: Optional[Dict[str, Any]] = None) -> str:
    """Generate the sample sheet whose STRUCTURE matches the analysis (from the config, no data).

    The columns + example rows are derived from the enabled modules so the user fills the right
    shape — a differential run gets a group column with two groups of two, a decontam run gets a
    control column with a blank/negative-control row, an aDNA run marks library=ancient. Short-read
    platforms show the paired-end form (r2 + layout=pe) so paired Illumina isn't silently single-end.
    """
    cfg = cfg or {}
    mods = cfg.get("modules", {}) or {}
    short = platform in _SHORT_PLATFORMS
    library = "ancient" if mods.get("damage") else "wgs"
    gcol = (str((cfg.get("differential") or {}).get("group_column", "group"))
            if mods.get("differential") else None)
    ctrl = bool(mods.get("decontam"))

    cols = ["sample", "r1", "r2", "platform", "layout", "library"]
    if gcol:
        cols.append(gcol)
    if ctrl:
        cols.append("control")

    def _reads(name: str):
        return ((f"reads/{name}_R1.fastq.gz", f"reads/{name}_R2.fastq.gz", "pe") if short
                else (f"reads/{name}.fastq.gz", "", "se"))

    def _row(name: str, group: str = "", control: str = "") -> str:
        r1, r2, lay = _reads(name)
        cells = [name, r1, r2, platform, lay, library]
        if gcol:
            cells.append(group)
        if ctrl:
            cells.append(control)
        return "\t".join(cells)

    rows = ["\t".join(cols)]
    if gcol:
        # differential needs >=2 groups with >=2 samples each — show exactly that shape
        rows += [_row("CASE1", "case"), _row("CASE2", "case"),
                 _row("CTRL1", "control"), _row("CTRL2", "control")]
    else:
        rows += [_row("SAMPLE1"), _row("SAMPLE2")]
    if ctrl:
        rows.append(_row("BLANK", control="true"))   # decontam needs a negative/blank control
    return "\n".join(rows) + "\n"


def _setup_sh(env_name: str, use_conda: bool, executor: Optional[str]) -> str:
    # a full echo command (not bare text) — inserted verbatim into the script below.
    conda_note = ('echo "   Heavier tools are built per-rule by metagx run --use-conda on first use '
                  '(isolated on purpose)."' if use_conda else
                  'echo "   Every tool this run needs is in the tailored env above — no per-rule envs."')
    slurm_edit = " and slurm_partition+account in profile/config.yaml" if executor else ""
    return f"""\
#!/usr/bin/env bash
# 00_setup.sh — environment-making step (fresh laptop OR HPC login node). Run once.
# Installs metagx (from GitHub; brings the Snakemake workflow) and builds a MINIMAL, collision-safe
# conda env for exactly THIS analysis. Prereqs: git + conda/mamba (Miniforge). Re-runnable.
#   WITH_SLURM=1 bash 00_setup.sh   # on an HPC that submits via SLURM
set -euo pipefail
METAGX_REPO="${{METAGX_REPO:-{METAGX_REPO_URL}}}"
METAGX_HOME="${{METAGX_HOME:-$HOME/metagx}}"
WITH_SLURM="${{WITH_SLURM:-0}}"

command -v git >/dev/null || {{ echo "ERROR: git required"; exit 1; }}
if   command -v mamba >/dev/null 2>&1; then CONDA=mamba
elif command -v conda >/dev/null 2>&1; then CONDA=conda
else echo "ERROR: need conda or mamba (Miniforge: https://github.com/conda-forge/miniforge)"; exit 1; fi

if ! command -v metagx >/dev/null 2>&1; then
  [ -d "$METAGX_HOME/.git" ] || git clone --depth 1 "$METAGX_REPO" "$METAGX_HOME"
  ( cd "$METAGX_HOME" && bash setup.sh )
  # shellcheck disable=SC1091
  source "$METAGX_HOME/.venv/bin/activate"
fi
command -v metagx >/dev/null || {{ [ -f "$METAGX_HOME/.venv/bin/activate" ] && source "$METAGX_HOME/.venv/bin/activate"; }}
command -v metagx >/dev/null || {{ echo "ERROR: metagx not installed"; exit 1; }}

if "$CONDA" env list | awk '{{print $1}}' | grep -qx "{env_name}"; then
  echo ">> conda env '{env_name}' already exists — skipping."
else
  echo ">> creating tailored conda env '{env_name}' from env.yaml"
  "$CONDA" env create -f env.yaml
fi

if [ "$WITH_SLURM" = "1" ]; then
  python -m pip install -q snakemake-executor-plugin-slurm 2>/dev/null \
    || uv pip install -q snakemake-executor-plugin-slurm 2>/dev/null \
    || echo "   (install snakemake-executor-plugin-slurm into metagx's venv manually)"
fi
metagx doctor || true
echo
echo "✅ Ready. tool env: {env_name}"
{conda_note}
echo "Next: edit samples.tsv{slurm_edit}, then: bash run.sh"
"""


def _run_sh(project: str, env_name: str, use_conda: bool, executor: Optional[str]) -> str:
    profile = " --profile profile" if executor else ""
    uc = " --use-conda" if use_conda else ""
    target = "SLURM" if executor else "locally"
    return f"""\
#!/usr/bin/env bash
# run.sh — {project}: preflight -> dry-run -> run {target}. Run 00_setup.sh first.
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v metagx >/dev/null 2>&1 && [ -f "${{METAGX_HOME:-$HOME/metagx}}/.venv/bin/activate" ]; then
  # shellcheck disable=SC1091
  source "${{METAGX_HOME:-$HOME/metagx}}/.venv/bin/activate"
fi
command -v metagx >/dev/null || {{ echo "ERROR: run 00_setup.sh first (installs metagx)"; exit 1; }}

# Put the tailored tool env on PATH by APPENDING its bin (not `conda activate`, which prepends its
# python and would shadow the venv python that holds metagx + snakemake).
CONDA=$(command -v mamba || command -v conda || true)
if [ -n "$CONDA" ]; then
  ENV_BIN="$("$CONDA" env list | awk -v e="{env_name}" '$1==e{{print $NF"/bin"}}')"
  [ -n "$ENV_BIN" ] && export PATH="$PATH:$ENV_BIN"
fi

echo ">> [1/3] Preflight"; metagx doctor --config config.yaml || true
echo ">> [2/3] Dry run";  metagx run --config config.yaml{profile}{uc} --dry-run
echo ">> [3/3] Run {target}"
{'echo "   set slurm_partition + slurm_account in profile/config.yaml, and fill samples.tsv first."' if executor else 'echo "   fill samples.tsv first."'}
read -r -p "   Proceed now? [y/N] " ok; [ "${{ok:-N}}" = "y" ] || {{ echo "   skipped."; exit 0; }}
metagx run --config config.yaml{profile}{uc}
echo ">> Done. Results in results/.  Provenance: metagx report --config config.yaml"
"""


def _readme(project: str, plan: Dict[str, Any], executor: Optional[str]) -> str:
    core = ", ".join(p.split()[0] for p in plan["core_packages"]) or "(none)"
    per = ", ".join(plan["per_rule_tools"]) or "(none)"
    where = "an HPC login node (WITH_SLURM=1)" if executor else "your machine"
    return f"""\
# {project} — generated by `metagx project`

A self-contained, runnable analysis. Generated by the tool, collision-safe by construction.

## Environment (per-config, collision-safe)
- **Tailored core env** (`env.yaml`, on PATH): {core}
- **Per-rule via `--use-conda`** (isolated envs, built on first use): {per}
- `use-conda` for this config: **{str(plan['use_conda']).lower()}** — turned on only because the
  run needs isolated tools; a pure-core run creates no per-rule envs.

## Run it (from {where})
```bash
{'WITH_SLURM=1 ' if executor else ''}bash 00_setup.sh     # installs metagx + builds env.yaml (once)
# edit samples.tsv (your read paths){'; set slurm_partition + slurm_account in profile/config.yaml' if executor else ''}
bash run.sh                 # preflight -> dry-run -> run
```

`config.yaml` is validated; `metagx doctor --config config.yaml` guards the DBs. The step-by-step
pipeline is metagx's bundled `workflow/Snakefile`; `metagx run` drives it.
"""


def scaffold(cfg: Dict[str, Any], outdir: str, executor: Optional[str] = None,
             platform: str = "illumina", env_yml_path: Optional[str] = None,
             writer=None) -> Dict[str, Any]:
    """Write the full analysis folder. ``writer(path, text)`` is injectable for tests (default:
    real disk writes). Returns a manifest {dir, files, plan}."""
    env_yml_path = env_yml_path or runner.environment_file_path()
    plan = plan_env(cfg, env_yml_path)
    project = str(cfg.get("project", "run"))

    # sample sheet: reference a template path so env/tool derivation can read platforms
    samples = cfg.get("samples")
    if not isinstance(samples, str):
        cfg = dict(cfg)
        cfg["samples"] = "samples.tsv"
    # env plan derives platforms from the sheet we are about to write, so recompute against it
    # by seeding the template platform into a transient inline view:
    inline_view = dict(cfg)
    inline_view["samples"] = [{"sample": "SAMPLE1", "r1": "reads/SAMPLE1.fastq.gz", "platform": platform}]
    plan = plan_env(inline_view, env_yml_path)

    files: Dict[str, str] = {
        "config.yaml": yaml.safe_dump(cfg, sort_keys=False),
        "samples.tsv": _samples_template(platform, cfg),
        "env.yaml": report.config_env_yaml(inline_view, env_yml_path, name=plan["env_name"]),
        "00_setup.sh": _setup_sh(plan["env_name"], plan["use_conda"], executor),
        "run.sh": _run_sh(project, plan["env_name"], plan["use_conda"], executor),
        "README.md": _readme(project, plan, executor),
    }
    if executor:
        prof = os.path.join(schedulers.profile_path(executor), "config.yaml")
        with open(prof) as fh:
            ptext = fh.read()
        # keep the profile's use-conda in lockstep with the plan
        ptext = _set_yaml_scalar(ptext, "use-conda", "true" if plan["use_conda"] else "false")
        files[os.path.join("profile", "config.yaml")] = ptext

    written: List[str] = []
    for rel, text in files.items():
        dest = os.path.join(outdir, rel)
        if writer is not None:
            writer(dest, text)
        else:
            os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
            with open(dest, "w") as fh:
                fh.write(text)
            if rel.endswith(".sh"):
                os.chmod(dest, 0o755)
        written.append(rel)
    if writer is None:
        os.makedirs(os.path.join(outdir, "reads"), exist_ok=True)
    return {"dir": outdir, "files": sorted(written), "plan": plan}


def _set_yaml_scalar(text: str, key: str, value: str) -> str:
    """Replace a top-level ``key: ...`` scalar line's value, preserving the rest of the file."""
    out = []
    for line in text.splitlines():
        if line.strip().startswith(f"{key}:") and not line.lstrip().startswith("#"):
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f"{indent}{key}: {value}")
        else:
            out.append(line)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")
